on:
  push:
    branches:
      - master

name: Tests

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Install latest npm
        run: npm install -g npm@latest
      - name: Check npm version
        run: npm -v
      - name: Install project dependencies
        run: npm ci
      - name: Run tests
        run: npm run test:all
